apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: insights-storage-broker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: insights-storage-broker
    app.kubernetes.io/part-of: insights-storage-broker
  name: insights-storage-broker4uqv
spec:
  port:
    targetPort: 9000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: insights-storage-broker
    weight: 100
status: {}
