apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: insights-storage-broker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: insights-storage-broker
    app.kubernetes.io/part-of: insights-storage-broker
  name: insights-storage-broker
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: insights-storage-broker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: insights-storage-broker
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/insights-storage-broker/insights-storage-broker@sha256:f557f747fcea7aeca59d1895c15433c66b30850a1e38f833fcef529ed0b0b151
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
status: {}
